"""added callback url

Revision ID: 78adf916d7e4
Revises: 7fc8ab1b5993
Create Date: 2026-02-08 08:25:22.558909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78adf916d7e4'
down_revision = '7fc8ab1b5993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callbackurl', sa.String(length=200), nullable=False))
        batch_op.drop_column('record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('callbackurl')

    # ### end Alembic commands ###
