"""added request log table

Revision ID: 7fc8ab1b5993
Revises: f004251d5c56
Create Date: 2026-02-02 19:33:36.698335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc8ab1b5993'
down_revision = 'f004251d5c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('req_source', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_logs')
    # ### end Alembic commands ###
