"""rem rec_src url

Revision ID: 9dfe0d1d0f9d
Revises: 78adf916d7e4
Create Date: 2026-02-08 08:32:56.508179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfe0d1d0f9d'
down_revision = '78adf916d7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('req_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
